dockerfile: Dockerfile.test

script: tox --skip-missing-interpreters

linter:
  - flake8
  - bandit

branch:
  - master

notification:
  email: tech@bosondata.com.cn
  slack_webhook: https://hooks.slack.com/services/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
