language: python

sudo: required
dist: trusty

matrix:
  include:
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y libffi-dev libssl-dev nodejs shellcheck

install:
  - npm install -g jscs eslint csslint sass-lint jsonlint stylelint eslint-plugin-react eslint-plugin-react-native babel-eslint
  - pip install -U tox

script: tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov
